version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - redis
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]  # Command to run the FastAPI app
    environment:
      - REDIS_HOST=redis

  worker:
    build: .
    depends_on:
      - redis
    command: ["python", "worker.py"]  # Command to run the RQ worker
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
