version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - QUEUES=default

  worker:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - QUEUES=default

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
